#!/bin/sh

# Test 1: Database Creation

tmp=$(mktemp)

./minidb new "$tmp"
data="$(hexdump "$tmp")"
expected="$(printf '0000000 444d 0042                              \n0000003')"

# Compare, byte for byte.
if [ "$data" != "$expected" ]; then
  echo 'Did not create a new DB correctly.' >&2
  echo 'Invalid Header:' >&2
  echo "$data" >&2
  echo 'Expected:' >&2
  echo "$expected" >&2
  rm "$tmp"
  exit 1
fi

rm "$tmp"

# End test 2.

# Test 1: Stat Non-Database

tmp=$(mktemp)

data="$(./minidb stat "$tmp")"
expected=$(printf 'File Statistics:\nNot a valid miniDB database file.')

# Compare, byte for byte.
if [ "$data" != "$expected" ]; then
  echo 'Did not stat a non-database file correctly.' >&2
  echo 'Received:' >&2
  echo "$data" >&2
  echo 'Expected:' >&2
  echo "$expected" >&2
  rm "$tmp"
  exit 1
fi

rm "$tmp"

# End test 2.
