#!/bin/sh

# Test 1: Database Creation

tmp=$(mktemp)

./minidb new "$tmp"
data="$(hexdump "$tmp")"
expected="$(printf '0000000 444d 0042                              \n0000003')"

# Compare, byte for byte.
if [ "$data" != "$expected" ]; then
  echo 'Did not create a new DB correctly.' >&2
  echo 'Invalid Header:' >&2
  echo "$data" >&2
  echo 'Expected:' >&2
  echo "$expected" >&2
  rm "$tmp"
  exit 1
fi
echo 'Pass: 1. Database Creation'

rm "$tmp"

# End test 1.

# Test 2: Stat Non-Database

tmp=$(mktemp)

data="$(./minidb stat "$tmp")"
expected=$(printf 'File Statistics:\nNot a valid miniDB database file.')

# Compare, byte for byte.
if [ "$data" != "$expected" ]; then
  echo 'Did not stat a non-database file correctly.' >&2
  echo 'Received:' >&2
  echo "$data" >&2
  echo 'Expected:' >&2
  echo "$expected" >&2
  rm "$tmp"
  exit 1
fi
echo 'Pass: 2. Stat Non-Database'

rm "$tmp"

# End test 2.

# Test 3: Stat Empty Database

tmp=$(mktemp)
./minidb new "$tmp"

data="$(./minidb stat "$tmp")"
expected=$(printf 'File Statistics:\nTables: 0\nRecords: 0')

# Compare, byte for byte.
if [ "$data" != "$expected" ]; then
  echo 'Did not stat an empty database file correctly.' >&2
  echo 'Received:' >&2
  echo "$data" >&2
  echo 'Expected:' >&2
  echo "$expected" >&2
  rm "$tmp"
  exit 1
fi
echo 'Pass: 3. Stat Empty Database'

rm "$tmp"

# End test 3.

# Test 4: Adding a table

tmp=$(mktemp)

./minidb new "$tmp"
./minidb modify "$tmp" new table HelloWorld 10

data="$(hexdump "$tmp")"
expected="$(printf '0000000 444d 1d42 6548 6c6c 576f 036f 040a     \n000000e')"

# Compare, byte for byte.
if [ "$data" != "$expected" ]; then
  echo 'Did not stat an empty database file correctly.' >&2
  echo 'Received:' >&2
  echo "$data" >&2
  echo 'Expected:' >&2
  echo "$expected" >&2
  rm "$tmp"
  exit 1
fi
echo 'Pass: 4. Adding a table'

rm "$tmp"

# End test 4
